# Generated by Django 5.2.16 on 2026-08-02 21:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("full_name", models.CharField(max_length=150)),
                ("professional_title", models.CharField(max_length=200)),
                ("headline", models.CharField(max_length=300)),
                ("short_introduction", models.TextField()),
                ("profile_photo", models.ImageField(upload_to="hero/")),
                (
                    "resume_pdf",
                    models.FileField(blank=True, null=True, upload_to="hero/resume/"),
                ),
                ("github_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Hero Section",
            },
        ),
    ]
