# Generated by Django 5.2.17 on 2026-08-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="MANOJ K.C.", max_length=100)),
                (
                    "availabilityBadge",
                    models.CharField(
                        default="Available for On-Site (Kathmandu) & Remote Roles",
                        max_length=255,
                    ),
                ),
                (
                    "typingTexts",
                    models.TextField(
                        default="Python & Django Backend Architect,FinTech Systems Integrator"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        default="REST APIs • Microservices • PostgreSQL • JWT Auth",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Specialized in architecting high-throughput REST APIs, resilient relational database schemas, and secure transaction pipelines."
                    ),
                ),
                (
                    "location",
                    models.CharField(default="Kathmandu, Nepal", max_length=100),
                ),
                ("hireMeUrl", models.CharField(default="#contact", max_length=255)),
                (
                    "profileImage",
                    models.CharField(default="/profile.jpg", max_length=255),
                ),
                ("full_name", models.CharField(default="MANOJ K.C.", max_length=100)),
                (
                    "professional_title",
                    models.CharField(
                        default="Python & Django Backend Architect", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="manoj@example.com", max_length=254),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
