# Generated by Django 5.2.16 on 2026-08-02 21:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("company_name", models.CharField(max_length=150)),
                ("role_title", models.CharField(max_length=150)),
                (
                    "location",
                    models.CharField(default="Remote / Kathmandu", max_length=100),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Leave blank if current role", null=True
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                (
                    "description",
                    models.TextField(help_text="Key responsibilities and achievements"),
                ),
                (
                    "technologies_used",
                    models.CharField(
                        help_text="Comma-separated list (e.g., Python, Django, React)",
                        max_length=250,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Experience Records",
                "ordering": ["display_order", "-start_date"],
            },
        ),
    ]
