# Generated by Django 5.2.16 on 2026-08-02 21:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LANG", "Programming Language"),
                            ("FW", "Framework / Library"),
                            ("DB", "Database"),
                            ("DEV", "DevOps & Cloud"),
                            ("TOOL", "Tools & Version Control"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "percentage",
                    models.PositiveIntegerField(
                        help_text="Proficiency percentage (e.g., 90)"
                    ),
                ),
                (
                    "experience_years",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '3+ Years'",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
    ]
